site_name: pyfairdatatools
site_description: Tools for AI-READI
site_author: FAIR Data Innovations Hub

repo_url: https://github.com/AI-READI/pyfairdatatools
edit_uri: https://github.com/AI-READI/pyfairdatatools/edit/main/docs

dev_addr: 127.0.0.1:3000

theme: readthedocs

markdown_extensions:
  - codehilite
  - admonition
  - toc:
      permalink: '
  - pymdownx.betterem
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.smartsymbols

nav:
  - Home: index.md
  - Modules:
      - Validate: modules/validate.md
      - Generate: modules/generate.md
  - Schemas:
      - Dataset Description: schemas/dataset_description.md
      - Readme: schemas/readme.md
      - Participants: schemas/participants.md
  - About:
      - Release Notes: about/changelog.md
      - Contributor Guide: about/contributing.md
      - License: about/license.md
