site_name: pyfairdatatools
site_description: Tools for AI-READI
site_author: FAIR Data Innovations Hub

repo_url: https://github.com/AI-READI/pyfairdatatools
edit_uri: https://github.com/AI-READI/pyfairdatatools/edit/main/docs

theme: readthedocs

markdown_extensions:
  - codehilite

nav:
  - Home: index.md
  - Advanced: advanced.md
  - About:
      - Release Notes: about/changelog.md
      - Contributor Guide: about/contributing.md
      - License: about/license.md
